name = "Seje2"
description = "A beautiful zola theme"
license = "MIT"
homepage = "https://github.com/eatradish/Seje2"
# The minimum version of Zola required
min_version = "0.15.0"
# An optional live demo URL
demo = "https://eatradish.github.io/Seje2"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
# show Chinese date format instead of normal date format
seje_chinese_date = true
# show summary instead of the whole article on the index page
seje_show_summary_only = false
# Google Font API mirror URLs (for China mainland users, try fonts.loli.net)
seje_font_mirror = "fonts.googleapis.com"
# whether use traditional Chinese style vertical layout
seje_vertical_layout = false
# additional custom fonts to include (must be in CSS font-family format)
seje_custom_fonts = ""
# whether enable darkmode. Possible values: auto, always, never
seje_darkmode = "auto"

# The theme author info: you!
[author]
name = "Mag Mell"
homepage = "https://blog.utopiosphere.net"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "mdo"
homepage = "https://markdotto.com/"
repo = "https://www.github.com/mdo/hyde"

[languages.en.translations]
title = "寫嘢"
home = "Home"
archives = "Archives"
about = "About"
rss = "RSS"
more = "More"
olderArticle = "Older Article"
newer = "Newer"
older = "Older"
loading = "Loading..."

[languages.zh-cn.translations]
title = "寫嘢"
home = "主页"
archives = "归档"
about = "关于"
rss = "订阅"
more = "查看全文"
olderArticle = "旧文"
newer = "上一篇"
older = "下一篇"
loading = "加载中..."

[languages.zh-tw.translations]
title = "寫嘢"
home = "主頁"
archives = "歸檔"
about = "關於"
rss = "訂閱"
more = "查看全文"
olderArticle = "舊文"
newer = "上一篇"
older = "下一篇"
loading = "加載中..."
